apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iot-ingress
  namespace: iot-project
spec:
  rules:
  - host: iot.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: reader-service
            port:
              number: 5000